### ISSUE TITLE
Cant start Integration after update to 2025.7

### ISSUE THREAD

**Issue by mathiasolofsson87** [thomasddn/ha-volvo-cars#165]
### What happened?

Integration wont start after 2025.7 update. Authentication had expired, restarted home assistant and after restart it's not possible to start the integration to reauthenticate.

Logs give the following error:
`Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 10:49:51 AM (1 occurrence)
Last logged: 10:49:51 AM

Error setting up entry Volvo XC60 (YV1UZBMTDK1295762) for volvo_cars
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvo_cars/__init__.py", line 104, in async_setup_entry
    await token_coordinator.async_schedule_refresh(True)
  File "/config/custom_components/volvo_cars/coordinator.py", line 395, in async_schedule_refresh
    await self._async_refresh_token(raise_on_auth_failed=True)
  File "/config/custom_components/volvo_cars/coordinator.py", line 430, in _async_refresh_token
    result = await self._auth_api.async_refresh_token(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._store.data["refresh_token"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/volvo_cars/volvo/auth.py", line 129, in async_refresh_token
    auth = await self._async_refresh_token(refresh_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvo_cars/volvo/auth.py", line 211, in _async_refresh_token
    return TokenResponse.from_dict(data)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/volvo_cars/volvo/models.py", line 58, in from_dict
    return cls(**class_data)
TypeError: TokenResponse.__init__() missing 1 required positional argument: 'refresh_token'`

Clicking the config wheel in the integration view gives the following error:
"Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

### API availability

Something else

### Car connection

Unspecified

### Installed integration version

1.5.4

### Additional information

all sensors are unavailable

### Diagnostics

```json

```

**Comment by rasmusbe** [comment]
I was just about to create the same issue, here is my logs (with debug logs activated):

```2025-07-04 10:56:01.680 DEBUG (MainThread) [custom_components.volvo_cars] **REDACTED** - Loading entry
2025-07-04 10:56:01.680 DEBUG (MainThread) [custom_components.volvo_cars.coordinator] **REDACTED** - Refreshing token
2025-07-04 10:56:01.681 DEBUG (MainThread) [custom_components.volvo_cars.volvo.auth] Request [token refresh]
2025-07-04 10:56:01.821 DEBUG (MainThread) [custom_components.volvo_cars.volvo.auth] Request [token refresh] status: 200
2025-07-04 10:56:01.821 DEBUG (MainThread) [custom_components.volvo_cars.volvo.auth] Request [token refresh] response: {'access_token': '**REDACTED**', 'id_token': '**REDACTED**', 'token_type': 'Bearer', 'expires_in': 1799}
2025-07-04 10:56:01.822 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Volvo XC40 (**REDACTED**) for volvo_cars
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvo_cars/__init__.py", line 104, in async_setup_entry
    await token_coordinator.async_schedule_refresh(True)
  File "/config/custom_components/volvo_cars/coordinator.py", line 395, in async_schedule_refresh
    await self._async_refresh_token(raise_on_auth_failed=True)
  File "/config/custom_components/volvo_cars/coordinator.py", line 430, in _async_refresh_token
    result = await self._auth_api.async_refresh_token(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._store.data["refresh_token"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/volvo_cars/volvo/auth.py", line 129, in async_refresh_token
    auth = await self._async_refresh_token(refresh_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvo_cars/volvo/auth.py", line 211, in _async_refresh_token
    return TokenResponse.from_dict(data)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/volvo_cars/volvo/models.py", line 58, in from_dict
    return cls(**class_data)
TypeError: TokenResponse.__init__() missing 1 required positional argument: 'refresh_token'
```

**Comment by lewiswatt** [comment]
I have the same issue, however I have not updated to 2025.7. Still on 2025.6.1

**Comment by denkyem** [comment]
Same issue

**Comment by richardbeumer** [comment]
Same issue here. Still on version `2025.6.3`. Maybe an issue with Volvo's backend?

**Comment by shodan65** [comment]
Same here

**Comment by simonedimarzio** [comment]
Same issue and same error logs also for me

**Comment by shodan65** [comment]
@thomasddn Perfectly fine. We all love your work.

**Comment by saimon46** [comment]
Having a look deeper the issue started after the update, way after, the integration was working this morning, running with 2025.7.0. What I saw was the reauthentication needed around 1h30min ago. When I did the authentication I got the error showed in the first message

**Comment by fwmone** [comment]
I can confirm that after updating to 2025.7.0 about a day and a half ago, it ran flawlessly until about half an hour ago. And: Thank you very much for your great work, which I really appreciate!

**Comment by iangregory** [comment]
I don't think the Home Assistant version is relevant. I have the same issue on `2025.6.3`

I had Volvo2MQTT installed, and that went into error this morning with a refresh token issue. It's that that caused me to notice that Volvo2MQTT was deprecated and install this addon. So it seems likely that the issue is on the Volvo side (or was caused by a change on the Volvo side), as it appears to affect both integrations.

**Comment by farpudo** [comment]
> I don't think the Home Assistant version is relevant. I have the same issue on `2025.6.3`
> 
> I had Volvo2MQTT installed, and that went into error this morning with a refresh token issue. It's that that caused me to notice that Volvo2MQTT was deprecated and install this addon. So it seems likely that the issue is on the Volvo side (or was caused by a change on the Volvo side), as it appears to affect both integrations.

Yeah same here

**Comment by RobPijpers** [comment]
I was indeed prompted to logon this morning to get a new OTP token, after entering the new OTP Volvo2MQTT didn't start.

**Comment by thomasddn** [comment]
I just released v1.5.5-b0 (as a pre-release) with a workaround to the missing `refresh_token`. This might only hold until your current `refresh_token` has become stale, after which you probably need to reauthenticate again with OTP.

At least, everyone can go to their normal routine for the moment! What a lunch code session can do, right?

**Comment by CryInt** [comment]
thx! fix worked!

**Comment by rasmusbe** [comment]
> I just released v1.5.5-b0 (as a pre-release) with a workaround to the missing `refresh_token`. This might only hold until your current `refresh_token` has become stale (7 days since last refresh), after which you probably need to reauthenticate again with OTP.
> 
> At least, everyone can go to their normal routine for the moment! What a lunch code session can do, right?

@thomasddn I have seen some oauth implementations where the refresh token remains the same, and valid, as long as you keep refreshing it. I hope it will be the case here 😄

**Comment by RobPijpers** [comment]
Maybe a stupid question, but how can I install v1.5.5-b0 from HACS?

**Comment by RobPijpers** [comment]
> Just go to the integration on hacs and click the three dot beside it and then select download after that select the version and proceed.

Thanks for your help, didn'd know you can install different versions from this option.
The fix worked for me to!

**Comment by fwmone** [comment]
Thanks for your quick help, the fix works for me! 😊

**Comment by FransOv** [comment]
Workaround works fine, Didn't even have to reauthenticate. Thanks for this integration and for the extremely quick response to issues.

**Comment by nmatei** [comment]
> Maybe a stupid question, but how can I install v1.5.5-b0 from HACS?

Left Menu: HACS Menu -> Volvo Cars -> "..." (top-right Corner) -> Redownload

**Comment by thomasddn** [comment]
I made a "normal" release, so HACS will eventually provide you the update automatically. It also contains #164.

**Comment by Vausp** [comment]
Thanks a lot for your extra lunch-session to fix this issue. Everything is running again...

**Comment by ahammas** [comment]
> > I don't think the Home Assistant version is relevant. I have the same issue on `2025.6.3`
> > 
> > I had Volvo2MQTT installed, and that went into error this morning with a refresh token issue. It's that that caused me to notice that Volvo2MQTT was deprecated and install this addon. So it seems likely that the issue is on the Volvo side (or was caused by a change on the Volvo side), as it appears to affect both integrations.
> 
> Yeah same here

Same, updated to 2025.7 to see if it fixed issue. Didn't.

**Comment by chirsbaer** [comment]
Thank you for a swift fix Thomas!

**Comment by bleara** [comment]
It was all working until yesterday morning but after lots of faffing because I thought it was just me I still get "The device is disabled by Config entry" for my Volvo Cars device. I can't find any way of enabling it as the enable is greyed out.
I too only migrated from Volvo2MQTT a week or so ago when I noticed it was deprecated.
Everyting is the latest version, 1.5.5 for Volvo Cars.

**Comment by thomasddn** [comment]
@bleara How weird it may sound, try to explicitly disable the integration and then enable it again. On the integration page, click the three vertical dots next to your vehicle and click disable. Then enable again.

**Comment by thomasddn** [comment]
Hi @akamming! The first time you authenticate, i.e. when you receive the OTP, then you still get a refresh token. It's the "token refresh" API that doesn't return a refresh token anymore. A refresh token is valid for seven days.

The workaround in my case is just that the refresh token is not a required field anymore in my model, and I'm just keep using the same refresh token over and over again. For as long that works. I'm hoping that Volvo will eventually return a refresh token when its validity is almost over.

If not, then users will need to re-authenticate again to get a new refresh token.

> Then hopefully i know how to fix the domoticz plugin

Leave the dark side my friend, and come to Home Assistant 😜

**Comment by akamming** [comment]
> Hi [@akamming](https://github.com/akamming)! The first time you authenticate, i.e. when you receive the OTP, then you still get a refresh token. It's the "token refresh" API that doesn't return a refresh token anymore. A refresh token is valid for seven days.
> 
> The workaround in my case is just that the refresh token is not a required field anymore in my model, and I'm just keep using the same refresh token over and over again. For as long that works. I'm hoping that Volvo will eventually return a refresh token when its validity is almost over.
> 
> If not, then users will need to re-authenticate again to get a new refresh token.

Tx, i suspected something like that so chnged the code that refresh token is Only updates when it is returned, but i’m not convinced it’s a structural solution. That’s why i asked the question. But I understand now  you came to the same conclusion…
> 
> > Then hopefully i know how to fix the domoticz plugin
> 
> Leave the dark side my friend, and come to Home Assistant 😜

I am stuk in the middle, using ha, but still using domoticz for the more advanced use cases (it’s much more flexible for scripting).

**Comment by bleara** [comment]
Thomas, yes weird but it worked. Thanks.

**Comment by HansKatsman** [comment]
sorry I overlooked your existing integration which was also at HA
With the latest HACS version its working again as before

**Comment by TacitRainbow** [comment]
First of all - thanks thomasddn for the updated version (1.10.6) - tried everythin (incl. roll-back of HA and re-install of Volvo2MQTT from https://github.com/Dielee/volvo2mqtt), but no luck. Volvo2MQTT is still unsucessfully trying to start:
ul 11 11:50:38 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.10.6
Jul 11 11:50:38 volvo2mqtt [106] - INFO: Using login from token file
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 45, in authorize
    refresh_token = data["refresh_token"]
                    ~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'

I do have an EX30, so maybe linked to the different App it using... could well be because it is quite powerful and Volvo may not have disabled the OTP on it. Anybody with an EX30 out there struggling as I do?

**Comment by lagge78** [comment]
> First of all - thanks thomasddn for the updated version (1.10.6) - tried everythin (incl. roll-back of HA and re-install of Volvo2MQTT from https://github.com/Dielee/volvo2mqtt), but no luck. Volvo2MQTT is still unsucessfully trying to start: ul 11 11:50:38 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.10.6 Jul 11 11:50:38 volvo2mqtt [106] - INFO: Using login from token file Traceback (most recent call last): File "/volvoAAOS2mqtt/main.py", line 15, in authorize() File "/volvoAAOS2mqtt/volvo.py", line 45, in authorize refresh_token = data["refresh_token"] ~~~~^^^^^^^^^^^^^^^^^ KeyError: 'refresh_token'
> 
> I do have an EX30, so maybe linked to the different App it using... could well be because it is quite powerful and Volvo may not have disabled the OTP on it. Anybody with an EX30 out there struggling as I do?

Still the wrong integration. This is not Volvo2MQTT that you are using. this is ha-volvo-cars
So you have to switch to this one or go to the Volvo2MQTT github for help with the problem above. :)

Br Fredrik

**Comment by akamming** [comment]
> So you have to switch to this one (see here https://github.com/thomasddn/ha-volvo-cars) or go to the Volvo2MQTT github for help with the problem above as its not the same. :)
> 
> Br Fredrik

Volvo2mqtt is no longer maintainer. So Poetin the issue there Will not help. Bit indeed start using this integration Will solve the issue

**Comment by TacitRainbow** [comment]
Sorry - my bad. Was indeed on the wrong thread... ha-volvo-cars works flawlessly also on an EX30 & is really easy to set up.

**Comment by thomasddn** [comment]
Volvo API sends a new refresh token again when refreshing the access token, so I consider this solved.
